import type { Metadata } from "next";
import { Geist, Geist_Mono,Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${manrope.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
